(() => {
'use strict';
const id=n=>document.getElementById(n),q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
if(!window.CHERRIFT_V055A||!window.UI)return console.error('[v0.5.5b] v0.5.5a required');
const enemies=window.CHERRIFT_V040?.enemies||{};
function panel(pid,title,sub,body){if(id(pid))return;id('app').insertAdjacentHTML('beforeend',`<section id="${pid}" class="panel hidden v055-panel"><header class="panel-head"><button class="back">←</button><div><h2>${title}</h2><p>${sub}</p></div></header>${body}</section>`)}
function normalize(s){s.profile=s.profile||{name:'Cherry Player',createdAt:Date.now()};s.discoveredEnemies=s.discoveredEnemies||{};return s}
function power(s){return 100+Object.values(s.equipped||{}).reduce((sum,g)=>sum+(CHERRIFT_V050?.itemPower?.(g)||0),0)}
function ensure(){panel('profileV055','Player Profile','Your long-term CHERRIFT progression.',`<div id="profileBodyV055" class="v055-profile"></div>`);panel('statisticsV055','Statistics','Lifetime account and combat records.',`<div id="statsBodyV055" class="v055-stat-grid"></div>`);panel('collectionV055','Collection','Gear, enemies, skins and worlds.',`<div class="v055-tabs"><button data-col-tab="gear">GEAR</button><button data-col-tab="enemies">ENEMIES</button><button data-col-tab="skins">SKINS</button><button data-col-tab="worlds">WORLDS</button></div><div id="collectionBodyV055" class="v055-collection-grid"></div>`);panel('bestiaryV055','Enemy Encyclopedia','Defeat enemies to reveal their records.',`<div id="bestiaryBodyV055" class="v055-collection-grid"></div>`);const nav=q('.menu-left .main-nav');if(nav&&!id('profileBtnV055'))[['profileV055','👤','PROFILE'],['statisticsV055','📊','STATISTICS'],['collectionV055','📚','COLLECTION'],['bestiaryV055','👹','BESTIARY']].forEach(([p,i,t],n)=>{const b=document.createElement('button');b.className='menu-btn';if(!n)b.id='profileBtnV055';b.dataset.open=p;b.innerHTML=`<span>${i}</span><i>${t}</i><em>VIEW</em><b>›</b>`;nav.appendChild(b)});const more=id('mobileMoreV055');if(more&&!q('[data-v055-open="profileV055"]',more))more.insertAdjacentHTML('beforeend',`<button data-v055-open="profileV055">👤<b>Profile</b></button><button data-v055-open="collectionV055">📚<b>Collection</b></button><button data-v055-open="statisticsV055">📊<b>Stats</b></button><button data-v055-open="bestiaryV055">👹<b>Bestiary</b></button>`)}
function renderProfile(){const s=normalize(UI.save),clears=Object.keys(s.clearedStages||{}).length,ach=Object.keys(s.achievements||{}).length,total=window.CHERRIFT_V052?.ACH?.length||10;id('profileBodyV055').innerHTML=`<section class="glass v055-profile-hero"><span>${CHERRIFT_DATA.skins.find(x=>x.id===s.selectedSkin)?.emoji||'🐰'}</span><div><h2>${s.profile.name}</h2><p>Player Level ${s.account?.level||1}</p><b>Power ${Math.round(power(s))}</b></div></section><div class="v055-stat-grid"><article><small>ACHIEVEMENTS</small><b>${ach}/${total}</b></article><article><small>STAGES</small><b>${clears}/${CHERRIFT_V040.stages.length}</b></article><article><small>DAYS PLAYED</small><b>${Math.max(1,Math.ceil((Date.now()-s.profile.createdAt)/86400000))}</b></article><article><small>TOTAL XP</small><b>${Math.floor(s.account?.totalXp||0)}</b></article></div>`}
function renderStats(){const s=CHERRIFT_V055A.normalize(UI.save),st=s.stats;id('statsBodyV055').innerHTML=Object.entries({Enemies:st.kills,Runs:st.runs,'Stage Clears':st.clears,'Boss Kills':st.bosses,'Coins Earned':st.coinsEarned,'Chests Opened':st.chests,'Gear Found':st.gearFound,'Best Time':UI.fmt?.(s.best?.time||0)||0}).map(([k,v])=>`<article class="glass"><small>${k}</small><b>${v}</b></article>`).join('')}
function renderBestiary(target=id('bestiaryBodyV055')){const s=normalize(UI.save);target.innerHTML=Object.entries(enemies).map(([key,e])=>{const seen=s.discoveredEnemies[key];return `<article class="glass v055-collect ${seen?'':'unknown'}"><span>${seen?(e.boss?'👑':'👾'):'?'}</span><b>${seen?e.name:'Unknown Enemy'}</b><small>${seen?`HP ${e.hp} · SPD ${e.speed}`:'Defeat to discover'}</small></article>`}).join('')}
function renderCollection(tab='gear'){const s=normalize(UI.save),body=id('collectionBodyV055');if(tab==='gear'){const all=[...(s.inventory||[]),...Object.values(s.equipped||{})];body.innerHTML=all.map(g=>`<article class="glass v055-collect"><span>${UI.gearEmoji(g)}</span><b>${g.rarity} ${g.slot}</b><small>Lv.${g.itemLevel||1}</small></article>`).join('')||'<p>No gear collected.</p>'}if(tab==='enemies')renderBestiary(body);if(tab==='skins')body.innerHTML=CHERRIFT_DATA.skins.map(x=>`<article class="glass v055-collect ${s.unlockedSkins.includes(x.id)?'':'unknown'}"><span>${s.unlockedSkins.includes(x.id)?x.emoji:'?'}</span><b>${s.unlockedSkins.includes(x.id)?x.name:'Unknown Skin'}</b></article>`).join('');if(tab==='worlds'){const worlds=[...new Set(CHERRIFT_V040.stages.map(x=>x.world))];body.innerHTML=worlds.map(w=>{const done=CHERRIFT_V040.stages.filter(x=>x.world===w).every(x=>s.clearedStages?.[x.id]);return `<article class="glass v055-collect ${done?'':'unknown'}"><span>🌍</span><b>World ${w}</b><small>${done?'Complete':'In progress'}</small></article>`}).join('')}}
const custom=['profileV055','statisticsV055','collectionV055','bestiaryV055'],prev=UI.open.bind(UI);UI.open=function(p,...a){if(custom.includes(p)){['menu','skins','gear','chests','settings','worlds','playerUpgrade','achievements','dailyQuests','loginRewards','shopV055',...custom].forEach(x=>id(x)?.classList.toggle('hidden',x!==p));document.body.classList.remove('is-playing');if(p==='profileV055')renderProfile();if(p==='statisticsV055')renderStats();if(p==='collectionV055')renderCollection();if(p==='bestiaryV055')renderBestiary();return}prev(p,...a);custom.forEach(x=>id(x)?.classList.add('hidden'))};document.addEventListener('click',e=>{const t=e.target.closest('[data-col-tab]');if(t)renderCollection(t.dataset.colTab)});const gp=CherriftGame.prototype,oldD=gp.damageEnemy;gp.damageEnemy=function(e,d){const before=e&&!e.dead,type=e?.enemyType||e?.type;oldD.call(this,e,d);if(before&&e.dead&&type)normalize(this.save).discoveredEnemies[type]=true};ensure();const oldInit=UI.init.bind(UI);UI.init=function(s,g){normalize(s);const r=oldInit(s,g);ensure();return r};window.CHERRIFT_V055B={version:'0.5.5b'};console.info('[CHERRIFT] v0.5.5b loaded');
})();
