(() => {
'use strict';
const id=n=>document.getElementById(n), q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
if(!window.UI||!window.CherriftStorage||!window.CHERRIFT_V053)return console.error('[v0.5.5a] v0.5.3 required');
if(!id('v055css')){const l=document.createElement('link');l.id='v055css';l.rel='stylesheet';l.href='v055.css?v=055';document.head.appendChild(l)}
const dayKey=()=>new Date().toISOString().slice(0,10);
const POOL=[
 {type:'kills',title:'Slime Cleanup',target:150,icon:'⚔️',reward:{coins:90}},
 {type:'runs',title:'Keep Moving',target:3,icon:'▶️',reward:{coins:120}},
 {type:'clears',title:'Stage Hunter',target:2,icon:'🗺️',reward:{coins:130}},
 {type:'coins',title:'Treasure Trail',target:40,icon:'🪙',reward:{coins:110}},
 {type:'chests',title:'Open Sesame',target:2,icon:'📦',reward:{coins:80,keys:1}},
 {type:'gear',title:'Gear Collector',target:4,icon:'🛡️',reward:{coins:100}},
 {type:'bosses',title:'Boss Breaker',target:1,icon:'👑',reward:{coins:180,keys:1}}
];
function panel(pid,title,sub,body){if(id(pid))return;id('app').insertAdjacentHTML('beforeend',`<section id="${pid}" class="panel hidden v055-panel"><header class="panel-head"><button class="back" data-v055-back>←</button><div><h2>${title}</h2><p>${sub}</p></div></header>${body}</section>`)}
function makeDaily(){return [...POOL].sort(()=>Math.random()-.5).slice(0,5).map((x,i)=>({...x,id:`${dayKey()}_${i}_${x.type}`,start:0,claimed:false}))}
function normalize(s){s.daily=s.daily||{};s.login=s.login||{};s.shop=s.shop||{};s.stats={kills:0,runs:0,clears:0,coinsEarned:0,chests:0,gearFound:0,bosses:0,...(s.stats||{})};if(s.daily.key!==dayKey())s.daily={key:dayKey(),quests:makeDaily(),claimedBonus:false,rerolls:1};if(!s.daily.quests?.length)s.daily.quests=makeDaily();s.login.firstDay=s.login.firstDay||dayKey();s.login.claimed=s.login.claimed||{};if(s.shop.key!==dayKey())s.shop={key:dayKey(),claims:{}};s.shop.claims=s.shop.claims||{};return s}
function progress(q,s){const map={kills:s.stats.kills,runs:s.stats.runs,clears:s.stats.clears,coins:s.stats.coinsEarned,chests:s.stats.chests,gear:s.stats.gearFound,bosses:s.stats.bosses};return Math.max(0,(map[q.type]||0)-(q.start||0))}
function reward(r){UI.save.coins+=(r.coins||0);UI.save.keys+=(r.keys||0)}
function save(){CherriftStorage.save(UI.save)}
function ensure(){
 panel('dailyQuests','Daily Quests','Five fresh objectives every day.',`<div class="v055-toolbar"><button id="dailyRerollV055">REROLL</button><button id="dailyClaimAllV055">CLAIM ALL</button></div><div id="dailyListV055" class="v055-card-grid"></div><div id="dailyBonusV055" class="glass v055-bonus"></div>`);
 panel('loginRewards','Login Rewards','A seven-day repeating reward track.',`<div id="loginListV055" class="v055-login-grid"></div>`);
 panel('shopV055','Shop','Daily freebies and simple purchases.',`<div id="shopListV055" class="v055-card-grid"></div>`);
 const nav=q('.menu-left .main-nav');if(nav&&!id('dailyBtnV055'))[['dailyQuests','📅','DAILY'],['shopV055','🛒','SHOP'],['loginRewards','🎁','LOGIN REWARD']].forEach(([p,i,t],n)=>{const b=document.createElement('button');b.className='menu-btn';if(!n)b.id='dailyBtnV055';b.dataset.open=p;b.innerHTML=`<span>${i}</span><i>${t}</i><em>NEW</em><b>›</b>`;nav.appendChild(b)});
 let more=id('mobileMoreV055');if(!more){more=document.createElement('div');more.id='mobileMoreV055';more.className='mobile-more-v055';more.innerHTML=`<button data-v055-open="dailyQuests">📅<b>Daily</b></button><button data-v055-open="shopV055">🛒<b>Shop</b></button><button data-v055-open="loginRewards">🎁<b>Login</b></button>`;document.body.appendChild(more)}
}
function renderDaily(){const s=normalize(UI.save);id('dailyListV055').innerHTML=s.daily.quests.map(x=>{const p=Math.min(x.target,progress(x,s)),done=p>=x.target;return `<article class="glass v055-card"><span>${x.icon}</span><div><h3>${x.title}</h3><p>${p}/${x.target}</p><div class="v055-progress"><i style="width:${p/x.target*100}%"></i></div><small>${x.reward.coins||0} coins${x.reward.keys?` · ${x.reward.keys} key`:''}</small></div><button data-daily-claim="${x.id}" ${!done||x.claimed?'disabled':''}>${x.claimed?'CLAIMED':'CLAIM'}</button></article>`}).join('');const c=s.daily.quests.filter(x=>x.claimed).length;id('dailyBonusV055').innerHTML=`<h3>Daily Completion Chest</h3><p>${c}/5 quests claimed</p><button id="dailyBonusClaimV055" ${c<5||s.daily.claimedBonus?'disabled':''}>${s.daily.claimedBonus?'CLAIMED':'CLAIM 250 COINS + 2 KEYS'}</button>`;id('dailyRerollV055').textContent=`REROLL (${s.daily.rerolls||0})`}
function renderLogin(){const R=[{coins:100},{keys:1},{coins:180},{keys:2},{coins:250},{keys:3},{coins:500,keys:2}],s=normalize(UI.save),d=Math.floor((Date.now()-new Date(s.login.firstDay).getTime())/86400000)%7;id('loginListV055').innerHTML=R.map((r,i)=>`<article class="glass v055-login ${i===d?'today':''}"><span>DAY ${i+1}</span><b>${r.coins?`${r.coins} 🪙`:''} ${r.keys?`${r.keys} 🗝️`:''}</b><button data-login-day="${i}" ${i!==d||s.login.claimed[dayKey()]?'disabled':''}>${s.login.claimed[dayKey()]&&i===d?'CLAIMED':i===d?'CLAIM':'LOCKED'}</button></article>`).join('')}
function renderShop(){const s=normalize(UI.save),O=[{id:'freeCoins',name:'Daily Coins',icon:'🪙',cost:0,reward:{coins:100}},{id:'freeKey',name:'Daily Key',icon:'🗝️',cost:0,reward:{keys:1}},{id:'keyPack',name:'Key Pack',icon:'📦',cost:350,reward:{keys:3}},{id:'coinBundle',name:'Coin Bundle',icon:'💰',cost:2,keyCost:true,reward:{coins:300}}];id('shopListV055').innerHTML=O.map(o=>`<article class="glass v055-shop-card"><span>${o.icon}</span><h3>${o.name}</h3><p>${o.reward.coins||0}${o.reward.coins?' coins':''} ${o.reward.keys||0}${o.reward.keys?' keys':''}</p><button data-shop="${o.id}" ${o.cost===0&&s.shop.claims[o.id]?'disabled':''}>${o.cost===0?(s.shop.claims[o.id]?'CLAIMED':'FREE'):o.keyCost?`${o.cost} KEYS`:`${o.cost} COINS`}</button></article>`).join('')}
const custom=['dailyQuests','loginRewards','shopV055'],prevOpen=UI.open.bind(UI);UI.open=function(p,...a){if(custom.includes(p)){['menu','skins','gear','chests','settings','worlds','playerUpgrade','achievements',...custom].forEach(x=>id(x)?.classList.toggle('hidden',x!==p));document.body.classList.remove('is-playing');if(p==='dailyQuests')renderDaily();if(p==='loginRewards')renderLogin();if(p==='shopV055')renderShop();return}prevOpen(p,...a);custom.forEach(x=>id(x)?.classList.add('hidden'))};
function buy(k){const s=normalize(UI.save),O={freeCoins:{cost:0,reward:{coins:100}},freeKey:{cost:0,reward:{keys:1}},keyPack:{cost:350,reward:{keys:3}},coinBundle:{cost:2,keyCost:true,reward:{coins:300}}},o=O[k];if(!o)return;if(!o.cost){if(s.shop.claims[k])return;s.shop.claims[k]=true}else if(o.keyCost){if(s.keys<o.cost)return UI.toast('Not enough keys');s.keys-=o.cost}else{if(s.coins<o.cost)return UI.toast('Not enough coins');s.coins-=o.cost}reward(o.reward);save();renderShop();UI.refreshMenu();UI.toast('Purchase complete')}
document.addEventListener('click',e=>{const o=e.target.closest('[data-v055-open]');if(o){UI.open(o.dataset.v055Open);return}const c=e.target.closest('[data-daily-claim]');if(c){const x=UI.save.daily.quests.find(v=>v.id===c.dataset.dailyClaim);if(x&&!x.claimed&&progress(x,UI.save)>=x.target){x.claimed=true;reward(x.reward);save();renderDaily();UI.refreshMenu()}return}if(e.target.id==='dailyBonusClaimV055'){const s=UI.save;if(s.daily.quests.every(x=>x.claimed)&&!s.daily.claimedBonus){s.daily.claimedBonus=true;reward({coins:250,keys:2});save();renderDaily();UI.refreshMenu()}return}if(e.target.id==='dailyClaimAllV055'){UI.save.daily.quests.forEach(x=>{if(!x.claimed&&progress(x,UI.save)>=x.target){x.claimed=true;reward(x.reward)}});save();renderDaily();UI.refreshMenu();return}if(e.target.id==='dailyRerollV055'){const s=UI.save;if(s.daily.rerolls>0){s.daily.rerolls--;s.daily.quests=makeDaily().map(x=>({...x,start:s.stats[x.type]||0}));save();renderDaily()}return}const l=e.target.closest('[data-login-day]');if(l){const R=[{coins:100},{keys:1},{coins:180},{keys:2},{coins:250},{keys:3},{coins:500,keys:2}],i=+l.dataset.loginDay;if(!UI.save.login.claimed[dayKey()]){reward(R[i]);UI.save.login.claimed[dayKey()]=true;save();renderLogin();UI.refreshMenu()}return}const sh=e.target.closest('[data-shop]');if(sh)buy(sh.dataset.shop)});
const gp=CherriftGame.prototype,oldD=gp.damageEnemy;gp.damageEnemy=function(e,d){const a=e&&!e.dead;oldD.call(this,e,d);if(a&&e.dead){normalize(this.save).stats.kills++;if(e.isBoss)this.save.stats.bosses++}};const oldC=gp.stageClear;gp.stageClear=function(...a){normalize(this.save).stats.clears++;return oldC.apply(this,a)};const oldS=gp.start;gp.start=async function(...a){normalize(this.save).stats.runs++;return oldS.apply(this,a)};const oldChest=UI.openChest?.bind(UI);if(oldChest)UI.openChest=function(...a){const n=this.save.inventory.length,r=oldChest(...a);if(this.save.inventory.length>n){normalize(this.save).stats.chests++;this.save.stats.gearFound++}return r};
ensure();const oldInit=UI.init.bind(UI);UI.init=function(s,g){normalize(s);const r=oldInit(s,g);ensure();return r};window.CHERRIFT_V055A={version:'0.5.5a',normalize};console.info('[CHERRIFT] v0.5.5a loaded');
})();
