(() => {
'use strict';
const id=n=>document.getElementById(n);
if(!window.CHERRIFT_V055B||!window.UI)return console.error('[v0.5.5c] v0.5.5b required');
const CONFIG={xpMultiplier:1,coinMultiplier:1,skinBonuses:{cherry_default:{coin:.05},fairy_cherry:{xp:.05},beastclaw_cherry:{crit:.02}},recommendedPower:{1:100,2:350,3:700},flags:{daily:true,shop:true,stars:true}};window.CHERRIFT_REMOTE_CONFIG=CONFIG;
const EXTRA=[{id:'stars10',name:'Rising Star',desc:'Earn 10 stage stars.',icon:'⭐',reward:{coins:250},test:s=>Object.values(s.stageStars||{}).reduce((a,b)=>a+b,0)>=10},{id:'stars20',name:'Star Collector',desc:'Earn 20 stage stars.',icon:'🌟',reward:{coins:500,keys:2},test:s=>Object.values(s.stageStars||{}).reduce((a,b)=>a+b,0)>=20},{id:'world3',name:'Savannah Hero',desc:'Clear World 3-5.',icon:'🦁',reward:{coins:700,keys:3},test:s=>!!s.clearedStages?.world_3_5},{id:'power1000',name:'Powerful Bloom',desc:'Reach 1000 total power.',icon:'💥',reward:{coins:350},test:s=>100+Object.values(s.equipped||{}).reduce((a,g)=>a+(CHERRIFT_V050?.itemPower?.(g)||0),0)>=1000}];if(window.CHERRIFT_V052?.ACH&&!CHERRIFT_V052.ACH.some(x=>x.id==='stars10'))CHERRIFT_V052.ACH.push(...EXTRA);
function normalize(s){s.stageStars=s.stageStars||{};return s}
function stars(game){let n=1;if((game.player?.hp||0)>0)n++;if((game.time||999)<150)n++;return n}
const gp=CherriftGame.prototype,oldClear=gp.stageClear;gp.stageClear=function(...a){const st=this.stage,n=stars(this),r=oldClear.apply(this,a);if(st){normalize(this.save).stageStars[st.id]=Math.max(this.save.stageStars[st.id]||0,n);CherriftStorage.save(this.save)}return r};const oldStart=gp.start;gp.start=async function(...a){const r=await oldStart.apply(this,a),b=CONFIG.skinBonuses[this.save.selectedSkin]||{};if(this.player){if(b.crit)this.player.crit+=b.crit;if(b.xp)this.player.xpBonus=b.xp;if(b.coin)this.player.coinBonus=b.coin}return r};const oldPick=gp.updatePickups;gp.updatePickups=function(dt){const before=this.save.coins;oldPick.call(this,dt);const gained=this.save.coins-before;if(gained>0){const b=CONFIG.skinBonuses[this.save.selectedSkin]?.coin||0;if(b){const extra=Math.floor(gained*b);this.save.coins+=extra;this.runCoins+=extra}CHERRIFT_V055A.normalize(this.save).stats.coinsEarned+=gained}};
const oldWorld=UI.renderWorldPanel?.bind(UI);if(oldWorld)UI.renderWorldPanel=function(...a){const r=oldWorld(...a),st=CHERRIFT_V040.stages[this.worldCarouselIndex||0];if(!st)return r;let box=id('worldPreviewV055');if(!box){box=document.createElement('div');box.id='worldPreviewV055';box.className='glass v055-world-preview';id('worldSelectedInfo')?.insertAdjacentElement('afterend',box)}const types=[...new Set(st.enemyPool||[])].map(x=>CHERRIFT_V040.enemies[x]?.name||x).slice(0,4),n=normalize(this.save).stageStars[st.id]||0;box.innerHTML=`<div><small>RECOMMENDED POWER</small><b>${CONFIG.recommendedPower[st.world]||900}</b></div><div><small>ENEMIES</small><b>${types.join(', ')||'Unknown'}</b></div><div><small>BOSS</small><b>${st.boss?(CHERRIFT_V040.enemies[st.boss]?.name||st.boss):'None'}</b></div><div><small>STARS</small><b>${'⭐'.repeat(n)}${'☆'.repeat(3-n)}</b></div>`;return r};
const oldSkin=UI.renderSkinCarousel.bind(UI);UI.renderSkinCarousel=function(...a){const r=oldSkin(...a),skin=CHERRIFT_DATA.skins[this.skinIndex],b=CONFIG.skinBonuses[skin?.id]||{};let el=id('skinBonusV055');if(!el){el=document.createElement('div');el.id='skinBonusV055';el.className='glass v055-skin-bonus';id('skinEquip')?.insertAdjacentElement('beforebegin',el)}const p=[];if(b.coin)p.push(`+${b.coin*100}% Coins`);if(b.xp)p.push(`+${b.xp*100}% XP`);if(b.crit)p.push(`+${b.crit*100}% Crit`);el.innerHTML=`<small>PASSIVE BONUS</small><b>${p.join(' · ')||'No passive bonus'}</b>`;return r};normalize(UI.save||{});window.CHERRIFT_V055C={version:'0.5.5c',CONFIG};console.info('[CHERRIFT] v0.5.5c loaded');
})();
